In [2]:
import pandas as pd

In [ ]:
#The objective is to predict demand during the initial days after a product is introduced in the store.
#Your objective is to **build a predictive model** that estimates the number of sales for each product in the test set, specifically for the first day.

In [4]:
catalog = pd.read_csv('catalog.csv')
catalog

,product,color,size,price,category,brand,material,weight,quantity,rating,warranty
0,0,DimGray,XL,23.63,fancy,Tran and Sons,couple,9.25,9,3.5,2 years
1,1,Violet,XL,67.73,other,Ferguson-Carter,animal,8.76,40,1.7,1 year
2,2,Lavender,S,706.90,fancy,"Lambert, Nguyen and Webb",book,8.21,97,1.9,3 years
3,3,SaddleBrown,M,671.69,fancy,"Kelley, Wheeler and Richardson",station,2.52,98,4.3,1 year
4,4,Violet,M,214.38,kitchen,Campbell-Smith,chair,7.84,13,4.0,2 years
...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,MediumBlue,M,806.17,other,Frazier Inc,show,3.20,84,1.7,6 months
1996,1996,Khaki,XL,393.45,sport,"Holder, Sanchez and Jackson",single,4.54,85,3.8,2 years
1997,1997,LightCyan,S,441.48,sport,Johnson Group,image,9.21,99,1.8,6 months
1998,1998,Navy,M,583.54,classic,Gillespie-Edwards,another,6.14,21,2.1,1 year
1999,1999,DeepPink,M,856.98,classic,Fleming-Tucker,instead,1.61,7,3.4,1 year

In [6]:
transactions = pd.read_csv('transactions.csv')
transactions

              date  product  sales
0       2023-01-01        0     50
1       2023-01-01        1     35
2       2023-01-01        2      4
3       2023-01-01        3     24
4       2023-01-01        4      8
...            ...      ...    ...
253995  2023-07-01     1995     24
253996  2023-07-01     1996     41
253997  2023-07-01     1997     18
253998  2023-07-01     1998     18
253999  2023-07-01     1999     15

[254000 rows x 3 columns]

In [34]:
warranty_map = {
    '2 years': 24,
    '1 year': 12,
    '3 years': 36,
    '6 months': 6
}

catalog['warranty_months'] = catalog['warranty'].map(warranty_map)

In [44]:
for cc in ['product', 'color', 'size', 'category', 'brand', 'material', 'warranty']:
    print(cc)
    print(catalog[cc].nunique())
    print(catalog[cc].min())
    print(catalog[cc].max())
    grouped = catalog.groupby(cc)['product'].count()
    print(grouped.describe())
    print('')

product
2000
0
1999
count    2000.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: product, dtype: float64

color
140
AliceBlue
YellowGreen
count    140.000000
mean      14.285714
std        3.805119
min        4.000000
25%       12.000000
50%       14.000000
75%       17.000000
max       24.000000
Name: product, dtype: float64

size
4
L
XL
count      4.000000
mean     500.000000
std       29.518356
min      472.000000
25%      478.750000
50%      495.500000
75%      516.750000
max      537.000000
Name: product, dtype: float64

category
7
classic
watches
count      7.000000
mean     285.714286
std       14.693698
min      271.000000
25%      276.000000
50%      284.000000
75%      289.500000
max      314.000000
Name: product, dtype: float64

brand
1901
Abbott, Smith and Thomas
Zuniga and Sons
count    1901.000000
mean        1.052078
std         0.284553
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         5.000000
Name: product, dtype: float64

material
852
American
yourself
count    852.000000
mean       2.347418
std        1.254447
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        8.000000
Name: product, dtype: float64

warranty
4
1 year
6 months
count      4.000000
mean     500.000000
std       16.268579
min      478.000000
25%      493.000000
50%      503.500000
75%      510.500000
max      515.000000
Name: product, dtype: float64

In [36]:
for nn in ['price', 'weight', 'quantity', 'rating', 'warranty_months']:
    print(nn)
    print(catalog[nn].describe())

price
count    2000.000000
mean      498.930835
std       289.937956
min        10.010000
25%       237.052500
50%       490.435000
75%       760.910000
max       999.560000
Name: price, dtype: float64
weight
count    2000.000000
mean        5.327210
std         2.747042
min         0.500000
25%         2.960000
50%         5.395000
75%         7.670000
max         9.990000
Name: weight, dtype: float64
quantity
count    2000.000000
mean       50.389500
std        28.599734
min         1.000000
25%        26.000000
50%        50.000000
75%        75.000000
max       100.000000
Name: quantity, dtype: float64
rating
count    2000.00000
mean        2.99445
std         1.17838
min         1.00000
25%         1.90000
50%         3.00000
75%         4.00000
max         5.00000
Name: rating, dtype: float64
warranty_months
count    2000.000000
mean       19.299000
std        11.432233
min         6.000000
25%         6.000000
50%        12.000000
75%        24.000000
max        36.000000
Name: warranty_months, dtype: float64

In [46]:
transactions

              date  product  sales
0       2023-01-01        0     50
1       2023-01-01        1     35
2       2023-01-01        2      4
3       2023-01-01        3     24
4       2023-01-01        4      8
...            ...      ...    ...
253995  2023-07-01     1995     24
253996  2023-07-01     1996     41
253997  2023-07-01     1997     18
253998  2023-07-01     1998     18
253999  2023-07-01     1999     15

[254000 rows x 3 columns]

In [48]:
transactions.groupby('date')['product'].count()

date
2023-01-01    1600
2023-01-02    1600
2023-01-03    1600
2023-01-04    1600
2023-01-05    1600
              ...
2023-06-27     400
2023-06-28     400
2023-06-29     400
2023-06-30     400
2023-07-01     400
Name: product, Length: 182, dtype: int64